import { FileText, TerminalSquare } from "lucide-react";

const logs = [
  ["14:51:16", "INFO", "Applying migration 20240520_add_user_preferences.sql"], ["14:51:19", "INFO", "Creating table user_preferences"], ["14:51:20", "INFO", "Creating index idx_user_preferences_user_id"], ["14:51:20", "DEBUG", "Executing query: CREATE INDEX CONCURRENTLY idx_user_pr…"], ["14:51:21", "INFO", "Backfill in progress (batch: 12,342 / 51,203)"], ["14:51:28", "INFO", "Backfill progress: 24.1% (12,342 / 51,203)"], ["14:51:35", "INFO", "Analyzing tables"], ["14:51:36", "INFO", "Migration applied successfully in 02:41.673"], ["14:51:36", "INFO", "Starting integrity checks"], ["14:51:36", "INFO", "Running check: schema_integrity", "PASS"], ["14:51:36", "INFO", "Running check: foreign_keys", "PASS"], ["14:51:36", "INFO", "Running check: row_preservation", "PASS"],
] as const;

export function EvidenceLog() {
  return <section className="dashboard-card min-w-0 overflow-hidden" aria-labelledby="evidence-heading"><div className="flex items-center justify-between gap-4 border-b border-[#e3eaf1] px-5 py-4"><div><p className="dashboard-kicker">Execution evidence</p><h2 id="evidence-heading" className="mt-1 text-base font-bold tracking-[-0.02em] text-[#1c2940]">Evidence &amp; Logs</h2></div><button type="button" className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-[#d6e1eb] bg-white px-3 py-1.5 text-xs font-semibold text-[#405067] shadow-sm transition hover:bg-[#f7f9fb]"><FileText size={14} className="text-[#5a7088]" />View full logs</button></div><div className="p-4 sm:p-5"><div className="overflow-hidden rounded-xl border border-[#dce6ee] bg-[#fbfcfe]"><div className="flex items-center gap-2.5 border-b border-[#e3eaf1] bg-white px-3.5 py-2.5"><span className="grid size-7 place-items-center rounded-md bg-[#edf5fa] text-[#2b718b]"><TerminalSquare size={15} /></span><div><p className="text-xs font-bold text-[#34445b]">Live log output</p><p className="mt-0.5 text-[10px] text-[#8290a2]">Migration rehearsal · streaming</p></div></div><div className="max-h-72 overflow-auto px-2.5 py-2"><div className="min-w-[440px] font-mono text-[11px] leading-5">{logs.map(([time, level, message, result]) => <div key={`${time}${message}`} className="grid grid-cols-[66px_54px_1px_minmax(0,1fr)_auto] items-center gap-3 rounded-md px-2 py-1 hover:bg-white"><span className="text-[#718096]">{time}</span><LogLevel level={level} /><span className="h-3.5 w-px bg-[#dbe4ec]" /><span className="truncate text-[#4d5b70]">{message}</span>{result ? <span className="rounded-full bg-[#e8f6ed] px-2 py-0.5 text-[10px] font-bold tracking-wide text-[#278050]">{result}</span> : <span />}</div>)}</div></div></div><p className="mt-3 flex items-center gap-2 px-1 text-xs text-[#718096]"><span className="size-1.5 animate-pulse rounded-full bg-[#37a66a]" />Streaming live logs…</p></div></section>;
}

function LogLevel({ level }: { level: "INFO" | "DEBUG" }) {
  const styles = level === "DEBUG" ? "bg-[#eaf4fb] text-[#28759d]" : "bg-[#eaf7ef] text-[#278050]";
  return <span className={`inline-flex w-fit justify-center rounded px-1.5 py-0.5 text-[10px] font-bold tracking-wide ${styles}`}>{level}</span>;
}
