import Link from "next/link";
import { FileText, TerminalSquare } from "lucide-react";
import type { RunLog } from "@/lib/database/logs";

export function EvidenceLog({ logs, rehearsalId }: { logs: RunLog[]; rehearsalId: string }) {
  return <section className="dashboard-card min-w-0 overflow-hidden" aria-labelledby="evidence-heading"><div className="flex items-center justify-between gap-4 border-b border-[#e3eaf1] px-5 py-4"><div><p className="dashboard-kicker">Execution evidence</p><h2 id="evidence-heading" className="mt-1 text-base font-bold tracking-[-0.02em] text-[#1c2940]">Evidence &amp; Logs</h2></div><Link href={`/rehearsals/${rehearsalId}`} className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-[#d6e1eb] bg-white px-3 py-1.5 text-xs font-semibold text-[#405067] shadow-sm transition hover:bg-[#f7f9fb]"><FileText size={14} className="text-[#5a7088]" />View full logs</Link></div><div className="p-4 sm:p-5"><div className="overflow-hidden rounded-xl border border-[#dce6ee] bg-[#fbfcfe]"><div className="flex items-center gap-2.5 border-b border-[#e3eaf1] bg-white px-3.5 py-2.5"><span className="grid size-7 place-items-center rounded-md bg-[#edf5fa] text-[#2b718b]"><TerminalSquare size={15} /></span><div><p className="text-xs font-bold text-[#34445b]">Run log</p><p className="mt-0.5 text-[10px] text-[#8290a2]">Sanitized server-side evidence</p></div></div><div className="max-h-72 overflow-auto px-2.5 py-2">{logs.length ? <div className="min-w-[440px] font-mono text-[11px] leading-5">{logs.slice(-12).map((log) => <div key={log.id} className="grid grid-cols-[72px_54px_1px_minmax(0,1fr)] items-center gap-3 rounded-md px-2 py-1 hover:bg-white"><span className="text-[#718096]">{new Date(log.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span><LogLevel level={log.level} /><span className="h-3.5 w-px bg-[#dbe4ec]" /><span className="truncate text-[#4d5b70]">{log.message}</span></div>)}</div> : <p className="p-6 text-center text-sm font-sans text-[#7c899b]">No persisted log entries yet.</p>}</div></div></div></section>;
}

function LogLevel({ level }: { level: string }) { return <span className={`inline-flex w-fit justify-center rounded px-1.5 py-0.5 text-[10px] font-bold tracking-wide ${level.toLowerCase() === "error" ? "bg-rose-50 text-rose-700" : level.toLowerCase() === "warning" ? "bg-amber-50 text-amber-700" : "bg-[#eaf7ef] text-[#278050]"}`}>{level}</span>; }
