"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { Check, ChevronRight, CircleAlert, CircleX, Clock3, ExternalLink, FileCode2, LoaderCircle, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import type { RehearsalDetail, RehearsalListItem } from "@/lib/database/rehearsal-views";
import type { ProgressState } from "@/lib/rehearsal-engine/stages";
import { canReviewRun } from "@/lib/approvals/policy";

const statusStyle: Record<string, string> = {
  completed: "bg-emerald-50 text-emerald-700 ring-emerald-200", approved: "bg-emerald-50 text-emerald-700 ring-emerald-200",
  blocked: "bg-amber-50 text-amber-700 ring-amber-200", failed: "bg-rose-50 text-rose-700 ring-rose-200",
  starting: "bg-blue-50 text-blue-700 ring-blue-200", ready: "bg-blue-50 text-blue-700 ring-blue-200", branching: "bg-blue-50 text-blue-700 ring-blue-200", sandbox_starting: "bg-blue-50 text-blue-700 ring-blue-200", migration_running: "bg-blue-50 text-blue-700 ring-blue-200", validating: "bg-blue-50 text-blue-700 ring-blue-200",
};

export function StatusPill({ status }: { status: string | null }) {
  const value = status ?? "queued";
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-semibold capitalize ring-1 ring-inset ${statusStyle[value] ?? "bg-slate-50 text-slate-600 ring-slate-200"}`}><span className="size-1.5 rounded-full bg-current" />{value.replaceAll("_", " ")}</span>;
}

function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)) : "—"; }
function shortSha(value: string) { return value.slice(0, 8); }

export function DashboardOverview({ items }: { items: RehearsalListItem[] }) {
  const active = items.filter((item) => item.runStatus && !["completed", "blocked", "failed"].includes(item.runStatus)).length;
  const completed = items.filter((item) => item.runStatus === "completed").length;
  const blocked = items.filter((item) => item.runStatus === "blocked").length;
  return <div className="space-y-6">
    <section className="rounded-2xl border border-[#dde5eb] bg-white px-6 py-7 sm:px-8">
      <p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#5c7380]">Migration control room</p>
      <div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h2 className="max-w-2xl text-3xl font-semibold tracking-[-0.04em] text-[#172033]">Every migration gets a rehearsal before it earns production.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#64748b]">Live evidence from the exact pull-request commit, reviewed as a single auditable run.</p></div><Link href="/rehearsals" className="inline-flex shrink-0 items-center gap-2 self-start rounded-lg bg-[#1f6071] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#164d5b] md:self-auto">View rehearsals <ChevronRight size={16} /></Link></div>
    </section>
    <section className="grid gap-3 sm:grid-cols-3">{[["Active", active, "Runs currently progressing"], ["Completed", completed, "Ready for a human decision"], ["Blocked", blocked, "Needs migration attention"]].map(([label, count, description]) => <div key={String(label)} className="rounded-xl border border-[#e1e7ed] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#788599]">{label}</p><p className="mt-3 text-3xl font-semibold tracking-[-.04em] text-[#172033]">{count}</p><p className="mt-1 text-xs text-[#738095]">{description}</p></div>)}</section>
    <RehearsalTable items={items.slice(0, 8)} title="Recent rehearsals" />
  </div>;
}

export function RehearsalTable({ items, title = "Rehearsals" }: { items: RehearsalListItem[]; title?: string }) {
  if (!items.length) return <section className="rounded-xl border border-dashed border-[#d8e2e9] bg-white px-6 py-16 text-center"><FileCode2 className="mx-auto size-7 text-[#7c98a5]" /><h2 className="mt-4 text-lg font-semibold text-[#243246]">No rehearsals yet</h2><p className="mt-2 text-sm text-[#738095]">Add a pull request through the server-side intake flow to begin.</p></section>;
  return <section className="overflow-hidden rounded-xl border border-[#e0e7ed] bg-white"><div className="flex items-center justify-between border-b border-[#e8edf1] px-5 py-4"><h2 className="text-sm font-semibold text-[#1d2939]">{title}</h2><span className="text-xs text-[#788599]">{items.length} shown</span></div><div className="overflow-x-auto"><table className="min-w-[940px] w-full text-left"><thead className="bg-[#fbfcfd] text-[10px] font-semibold uppercase tracking-[.09em] text-[#788599]"><tr>{["Repository / PR", "Migration", "Commit", "Latest status", "Last run", "Created", ""].map((heading) => <th key={heading} className="px-5 py-3">{heading}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-[#eef2f5] text-sm text-[#455468] transition hover:bg-[#fbfcfd]"><td className="px-5 py-4"><Link href={`/rehearsals/${item.id}`} className="font-semibold text-[#214f60] hover:underline">{item.repoOwner}/{item.repoName}</Link><span className="ml-2 text-[#6b7b8e]">PR #{item.prNumber}</span></td><td className="max-w-[230px] truncate px-5 py-4 font-mono text-xs text-[#56677b]">{item.migrationPath ?? "No SQL migration detected"}</td><td className="px-5 py-4 font-mono text-xs text-[#56677b]">{shortSha(item.commitSha)}</td><td className="px-5 py-4"><StatusPill status={item.runStatus ?? item.rehearsalStatus} /></td><td className="px-5 py-4 text-xs">{formatDate(item.completedAt ?? item.runCreatedAt)}</td><td className="px-5 py-4 text-xs">{formatDate(item.createdAt)}</td><td className="px-5 py-4"><Link aria-label={`Open rehearsal ${item.id}`} href={`/rehearsals/${item.id}`} className="text-[#2a6779]"><ChevronRight size={17} /></Link></td></tr>)}</tbody></table></div></section>;
}

const stateDot: Record<ProgressState, string> = { completed: "bg-emerald-500", current: "bg-blue-500", pending: "bg-slate-200", blocked: "bg-amber-500", failed: "bg-rose-500", warning: "bg-amber-400" };
export function RehearsalDetailView({ rehearsal }: { rehearsal: RehearsalDetail }) {
  const router = useRouter();
  const active = rehearsal.runStatus && !["completed", "blocked", "failed"].includes(rehearsal.runStatus);
  useEffect(() => { if (!active) return; const timer = window.setInterval(() => router.refresh(), 5000); return () => window.clearInterval(timer); }, [active, router]);
  return <div className="space-y-5"><section className="rounded-xl border border-[#dfe7ed] bg-white px-6 py-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div><Link href="/rehearsals" className="text-xs font-semibold text-[#317083] hover:underline">← All rehearsals</Link><h2 className="mt-3 text-2xl font-semibold tracking-[-.035em] text-[#172033]">{rehearsal.repoOwner}/{rehearsal.repoName} <span className="text-[#748195]">· PR #{rehearsal.prNumber}</span></h2><p className="mt-2 flex items-center gap-2 font-mono text-xs text-[#64748b]"><FileCode2 size={14} />{rehearsal.migrationPath ?? "No migration path"}</p></div><div className="text-left lg:text-right"><StatusPill status={rehearsal.runStatus ?? rehearsal.rehearsalStatus} /><p className="mt-3 font-mono text-xs text-[#66758a]">{shortSha(rehearsal.commitSha)} · {formatDate(rehearsal.runCreatedAt ?? rehearsal.createdAt)}</p></div></div></section>
    <section className="rounded-xl border border-[#e0e7ed] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-[#1d2939]">Rehearsal progress</p><p className="mt-1 text-xs text-[#778599]">Derived from persisted engine evidence.</p></div><Clock3 className="size-5 text-[#78909a]" /></div><ol className="mt-7 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{rehearsal.stages.map((stage) => <li key={stage.key} className="flex items-center gap-3"><span className={`grid size-7 shrink-0 place-items-center rounded-full ${stateDot[stage.state]} ${stage.state === "pending" ? "text-slate-500" : "text-white"}`}>{stage.state === "completed" ? <Check size={14} strokeWidth={3} /> : stage.state === "failed" ? <CircleX size={14} /> : stage.state === "blocked" ? <CircleAlert size={14} /> : <span className="size-1.5 rounded-full bg-current" />}</span><div><p className="text-sm font-medium text-[#354157]">{stage.label}</p><p className="text-[11px] capitalize text-[#7c899b]">{stage.state}</p></div></li>)}</ol></section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_330px]"><div className="space-y-5"><EvidencePanel evidence={rehearsal.evidence} /><LogPanel logs={rehearsal.logs} /></div><ApprovalCard runId={rehearsal.runId} runStatus={rehearsal.runStatus} approval={rehearsal.approval} /></div>
  </div>;
}

function EvidencePanel({ evidence }: { evidence: RehearsalDetail["evidence"] }) { return <section className="rounded-xl border border-[#e0e7ed] bg-white"><div className="border-b border-[#e8edf1] px-5 py-4"><h3 className="text-sm font-semibold text-[#1d2939]">Evidence</h3></div>{evidence.length ? <ul className="divide-y divide-[#eef2f5]">{evidence.map((item) => <li key={item.id} className="flex items-start justify-between gap-4 px-5 py-4"><div><p className="text-sm font-medium text-[#354157]">{item.name.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-[#728095]">{item.type}</p></div><StatusPill status={item.status} /></li>)}</ul> : <p className="px-5 py-10 text-center text-sm text-[#788599]">Evidence will appear when a run records it.</p>}</section>; }
function LogPanel({ logs }: { logs: RehearsalDetail["logs"] }) { return <section className="rounded-xl border border-[#e0e7ed] bg-white"><div className="border-b border-[#e8edf1] px-5 py-4"><h3 className="text-sm font-semibold text-[#1d2939]">Run log</h3></div>{logs.length ? <ol className="divide-y divide-[#eef2f5]">{logs.map((log) => <li key={log.id} className="grid grid-cols-[82px_64px_1fr] gap-3 px-5 py-3 text-xs"><time className="font-mono text-[#788599]">{formatDate(log.createdAt)}</time><span className="font-semibold uppercase text-[#2e6978]">{log.level}</span><span className="text-[#4c5d70]">{log.message}</span></li>)}</ol> : <p className="px-5 py-10 text-center text-sm text-[#788599]">No log records were persisted for this run.</p>}</section>; }

function ApprovalCard({ runId, runStatus, approval }: { runId: string | null; runStatus: string | null; approval: RehearsalDetail["approval"] }) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function decide(decision: "approved" | "rejected") { if (!runId) return; setLoading(true); setError(""); try { const response = await fetch(`/api/runs/${runId}/approval`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision }) }); if (!response.ok) throw new Error("The decision could not be saved."); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The decision could not be saved."); } finally { setLoading(false); } }
  if (approval) return <aside className="rounded-xl border border-[#dce6df] bg-white p-5"><ShieldCheck className="size-5 text-emerald-600" /><h3 className="mt-3 text-sm font-semibold text-[#1d2939]">Decision recorded</h3><p className="mt-2 text-sm capitalize text-[#5d6c7c]">{approval.decision} by {approval.actor}</p><p className="mt-3 text-xs leading-5 text-[#788599]">This records the review only. It does not execute a production migration.</p></aside>;
  const enabled = canReviewRun(runStatus as "completed" | "blocked" | "failed" | null, false) && Boolean(runId); return <aside className="rounded-xl border border-[#e0e7ed] bg-white p-5"><ShieldCheck className="size-5 text-[#2f6d7d]" /><h3 className="mt-3 text-sm font-semibold text-[#1d2939]">Human decision</h3><p className="mt-2 text-sm leading-6 text-[#68778a]">A completed rehearsal can be approved or rejected. Neither action touches production.</p><div className="mt-5 grid gap-2"><button disabled={!enabled || loading} onClick={() => decide("approved")} className="rounded-lg bg-[#236778] px-3 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{loading ? <LoaderCircle className="mx-auto size-4 animate-spin" /> : "Approve rehearsal"}</button><button disabled={!enabled || loading} onClick={() => decide("rejected")} className="rounded-lg border border-[#d8e1e8] px-3 py-2.5 text-sm font-semibold text-[#536477] disabled:cursor-not-allowed disabled:opacity-40">Reject</button></div>{!enabled && <p className="mt-3 text-xs text-[#8a6370]">Only completed runs can be reviewed.</p>}{error && <p role="alert" className="mt-3 text-xs text-rose-600">{error}</p>}</aside>;
}
