import { CheckCircle2, CircleAlert, CircleX, Ellipsis, GitPullRequest, Layers3 } from "lucide-react";

const runs = [
  ["#1732", "feature/add-notifications", "#1268", "Add notifications table and backfill", "Alex Kim", "AK", "Completed", "Pass", "6m 12s", "2h ago"],
  ["#1731", "feature/update-indexes", "#1265", "Add indexes for performance", "Sam Lee", "SL", "Completed", "Pass", "4m 33s", "3h ago"],
  ["#1730", "hotfix/fix-null-constraint", "#1264", "Fix NULL constraint on orders", "Maria Johnson", "MJ", "Completed", "Pass", "3m 18s", "1d ago"],
  ["#1729", "feature/user-roles", "#1263", "Add user roles and permissions", "Alex Kim", "AK", "Completed", "Warning", "7m 41s", "2d ago"],
  ["#1728", "feature/audit-logs", "#1262", "Add audit logs table", "Sam Lee", "SL", "Blocked", "Blocked", "2m 09s", "2d ago"],
] as const;

export function RecentRuns() {
  return <section className="dashboard-card overflow-hidden" aria-labelledby="runs-heading"><div className="flex items-center justify-between border-b border-[#e7edf3] px-5 py-4"><h2 id="runs-heading" className="text-sm font-bold tracking-[-0.015em]">Recent runs</h2><button type="button" className="text-xs font-semibold text-[#286078] hover:underline">View history</button></div><div className="overflow-x-auto"><table className="min-w-[1060px] w-full text-left"><thead className="border-b border-[#e7edf3] text-[10px] font-bold uppercase tracking-wide text-[#7b8799]"><tr>{["Run ID", "Branch / PR", "Description", "Environment", "Triggered by", "Status", "Result", "Duration", "Started", ""].map((heading) => <th key={heading} className="whitespace-nowrap px-4 py-3 first:pl-5">{heading}</th>)}</tr></thead><tbody>{runs.map(([id, branch, pr, description, person, initials, status, result, duration, started]) => <tr key={id} className="border-b border-[#edf1f5] text-xs text-[#4b586c] last:border-0 hover:bg-[#fbfcfd]"><td className="whitespace-nowrap px-4 py-3 first:pl-5"><span className="rounded bg-[#eaf0f6] px-1.5 py-1 font-bold text-[#48566d]">{id}</span></td><td className="whitespace-nowrap px-4 py-3"><span className="font-medium">{branch}</span> <span className="ml-2 font-semibold text-[#3168aa]">{pr}</span> <GitPullRequest className="ml-1 inline size-3.5 text-[#69768a]" /></td><td className="px-4 py-3">{description}</td><td className="whitespace-nowrap px-4 py-3"><span className="inline-flex items-center gap-1.5"><Layers3 size={14} className="text-[#39846a]" />Neon (us-east-1)</span></td><td className="whitespace-nowrap px-4 py-3"><span className="inline-flex items-center gap-2"><span className="grid size-6 place-items-center rounded-full bg-[#edf0f4] text-[9px] font-bold text-[#587087]">{initials}</span>{person}</span></td><td className={`whitespace-nowrap px-4 py-3 ${status === "Blocked" ? "text-[#cc4a47]" : "text-[#5c6a7c]"}`}><span className={`mr-1.5 inline-block size-1.5 rounded-full ${status === "Blocked" ? "bg-[#eb5753]" : "bg-[#41a46c]"}`} />{status}</td><td className="whitespace-nowrap px-4 py-3"><Result result={result} /></td><td className="whitespace-nowrap px-4 py-3">{duration}</td><td className="whitespace-nowrap px-4 py-3">{started}</td><td className="px-4 py-3"><button type="button" aria-label={`More actions for ${id}`}><Ellipsis size={17} /></button></td></tr>)}</tbody></table></div></section>;
}

function Result({ result }: { result: string }) { const config = result === "Pass" ? [CheckCircle2, "text-[#25804e]"] : result === "Warning" ? [CircleAlert, "text-[#d58a04]"] : [CircleX, "text-[#d64b48]"]; const [Icon, color] = config as [typeof CheckCircle2, string]; return <span className={`inline-flex items-center gap-1.5 font-medium ${color}`}><Icon size={14} />{result}</span>; }
